{
 "title": "External Secrets",
 "description": "Prometheus metrics for External Secrets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_active_workers,job)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{job=\"$job\"},controller)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(externalsecret_sync_calls_total{job=\"$job\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$controller controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "controller" },
  {
   "title": "Active Workers $controller",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=~\"$job\", controller=~\"$controller\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Max Concurrent Reconciles $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles{job=~\"$job\", controller=~\"$controller\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller, result) (rate(controller_runtime_reconcile_total{job=~\"$job\", controller=~\"$controller\"}[2m]))",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Errors Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (rate(controller_runtime_reconcile_errors_total{job=~\"$job\", controller=~\"$controller\"}[2m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Runtime Recincile Time $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99% - {{controller}}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95% - {{controller}}"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90% - {{controller}}"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50% - {{controller}}"
    }
   ]
  },
  { "title": "$controller workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "controller" },
  {
   "title": "Depth $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "workqueue_depth{job=~\"$job\", name=~\"$controller\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Adds Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(workqueue_adds_total{job=~\"$job\", name=~\"$controller\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Longest Running Processor $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{job=~\"$job\", name=~\"$controller\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Retries Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(workqueue_retries_total{job=~\"$job\", name=~\"$controller\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unfinished Work $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{job=~\"$job\", name=~\"$controller\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Duration $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50% - {{name}}"
    }
   ]
  },
  {
   "title": "Queue Duration $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50% - {{name}}"
    }
   ]
  },
  { "title": "$name external secret", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }, "repeat": "name" },
  {
   "title": "Sync Calls Rate $name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (name, exported_namespace) (rate(externalsecret_sync_calls_total{job=~\"$job\", name=~\"$name\"}[2m]))",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Sync Calls Error Rate $name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 61 },
   "targets": [
    {
     "expr": "sum by (name, exported_namespace) (rate(externalsecret_sync_calls_error{job=~\"$job\", name=~\"$name\"}[2m]))",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "externalsecret_reconcile_duration{job=~\"$job\", name=~\"$name\"}",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Status $name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "externalsecret_status_condition{job=~\"$job\", name=~\"$name\", condition=\"Ready\", status=\"True\"}",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  }
 ]
}