{
 "title": "AWS Network Load Balancer (NLB)",
 "description": "Visualize AWS Network Load Balancer metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/NetworkELB, ActiveFlowCount ,LoadBalancer)"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy / Unhealthy Hosts Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Net /Active Flow Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ActiveFlowCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewFlowCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "New / Active Flow Count TLS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewFlowCount_TLS",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ActiveFlowCount_TLS",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ConsumedLCUs / ProcessedBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetTLSNegotiationErrorCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TCP_Client_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TCP_ELB_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TCP_Target_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 43 },
   "content": "<a href=\"http://verygoodsecurity.com\" target=\"_blank\" title=\"Dashboard maintained by Very Good Security\"><img src=\"https://www.verygoodsecurity.com/theme/img/meta-logo.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html\">AWS CloudWatch Network ELB documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/\">Installed from Grafana.com dashboards</a>"
  }
 ]
}