{
 "title": "F5 BIG-IP Dashboard",
 "description": "Main BIGIP Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "job", "label": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job='$job'},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Device System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_cpu{job='$job', instance='$instance'}",
     "legendFormat": "systemCPU"
    },
    {
     "expr": "f5_system_tmmCpu{job='$job', instance='$instance'}",
     "legendFormat": "tmmCpu"
    },
    {
     "expr": "f5_system_memory{job='$job', instance='$instance'}",
     "legendFormat": "systemMemory"
    },
    {
     "expr": "f5_system_tmmMemory{job='$job', instance='$instance'}",
     "legendFormat": "tmmMemory"
    }
   ]
  },
  {
   "title": "Performance Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_clientBitsIn_average{job='$job', instance='$instance'}",
     "legendFormat": "clientBitsIn"
    },
    {
     "expr": "f5_system_throughputPerformance_clientBitsOut_average{job='$job', instance='$instance'}",
     "legendFormat": "clientBitsOut"
    },
    {
     "expr": "f5_system_throughputPerformance_serverBitsIn_average{job='$job', instance='$instance'}",
     "legendFormat": "serverBitsIn"
    },
    {
     "expr": "f5_system_throughputPerformance_serverBitsOut_average{job='$job', instance='$instance'}",
     "legendFormat": "serverBitsOut"
    }
   ]
  },
  {
   "title": "Curcurrent Connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_client_average{job='$job', instance='$instance'}",
     "legendFormat": "client curConn"
    },
    {
     "expr": "f5_system_connectionsPerformance_server_average{job='$job', instance='$instance'}",
     "legendFormat": "server curConn"
    },
    {
     "expr": "f5_system_connectionsPerformance_activeSslClientConnections_average{job='$job', instance='$instance'}",
     "legendFormat": "SSL curConn"
    }
   ]
  },
  {
   "title": "New Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_clientConnections_average{job='$job', instance='$instance'}",
     "legendFormat": "client CPS"
    },
    {
     "expr": "f5_system_connectionsPerformance_serverConnections_average{job='$job', instance='$instance'}",
     "legendFormat": "server CPS"
    },
    {
     "expr": "f5_system_connectionsPerformance_newSslClientConnections_average{job='$job', instance='$instance'}",
     "legendFormat": "SSL TPS"
    },
    {
     "expr": "f5_system_connectionsPerformance_httpRequests_average{job='$job', instance='$instance'}",
     "legendFormat": "HTTP QPS"
    }
   ]
  },
  { "title": "Application Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Member Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_activeMemberCnt{pools=~\".+\", job='$job', instance='$instance'}) / count(f5_port{job='$job', instance='$instance'})"
    }
   ]
  },
  {
   "title": "Virtual Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_isEnabled{virtualServers=~\".+\", job='$job', instance='$instance'})"
    }
   ]
  },
  {
   "title": "Top Virtual Servers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(f5_totRequests{virtualServers=~\".+\", job='$job', instance='$instance'}[$__range])) by (virtualServers)"
    },
    {
     "expr": "sum (increase(f5_clientside_bitsOut{virtualServers=~\".+\", job='$job', instance='$instance'}[$__range])) by (virtualServers)"
    },
    {
     "expr": "sum (increase(f5_clientside_bitsIn{virtualServers=~\".+\", job='$job', instance='$instance'}[$__range])) by (virtualServers)"
    },
    {
     "expr": "sum (increase(f5_clientside_totConns{virtualServers=~\".+\", job='$job', instance='$instance'}[$__range])) by (virtualServers)"
    },
    {
     "expr": "f5_clientside_curConns{virtualServers=~\".+\", job='$job', instance='$instance'}"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_2xxResp{job='$job', instance='$instance'}[$__range]))"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_3xxResp{job='$job', instance='$instance'}[$__range]))"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_activeMemberCnt{pools=~\".+\", job='$job', instance='$instance'})"
    }
   ]
  },
  {
   "title": "Pod Members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_port{job='$job', instance='$instance'})"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_4xxResp{job='$job', instance='$instance'}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(f5_5xxResp{job='$job', instance='$instance'}[$__range]))"
    }
   ]
  },
  { "title": "Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Virtual Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "f5_clientside_curConns{job='$job', instance='$instance'}",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Virtual Server Available",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(f5_isEnabled{virtualServers=~\".+\", job='$job', instance='$instance'} ) by (virtualServers)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(f5_isAvailable{virtualServers=~\".+\", job='$job', instance='$instance'} + 2) by (virtualServers)"
    }
   ]
  },
  {
   "title": "Virtual Server Traffic In/Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsIn{virtualServers=~\".+\", job='$job', instance='$instance'}[$__rate_interval])",
     "legendFormat": "Bits-In {{virtualServers}}"
    },
    {
     "expr": "rate(f5_clientside_bitsOut{virtualServers=~\".+\", job='$job', instance='$instance'}[$__rate_interval])",
     "legendFormat": "Bits-Out {{virtualServers}}"
    }
   ]
  },
  {
   "title": "Virtual Server CPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(f5_clientside_totConns{virtualServers=~\".+\", job='$job', instance='$instance'}[1m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "HTTP Transactions over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "rate(f5_totRequests{virtualServers=~\".+\", job='$job', instance='$instance'}[1m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  },
  {
   "title": "Top Pools",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(f5_totRequests{pools=~\".+\", members=\"\", job='$job', instance='$instance'}[$__range])) by (pools)"
    },
    {
     "expr": "sum (increase(f5_serverside_bitsOut{pools=~\".+\", members=\"\",  job='$job', instance='$instance'}[$__range]) + increase(f5_serverside_bitsIn{pools=~\".+\", members=\"\",  job='$job', instance='$instance'}[$__range]) ) by (pools)"
    }
   ]
  },
  {
   "title": "Pool Healthy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pools) (f5_activeMemberCnt{ job='$job', instance='$instance'}) / count by (pools) (f5_port{pools=~\".+\", job='$job', instance='$instance'})",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Pool Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "f5_serverside_curConns{job='$job', instance='$instance', members=~\"\"}",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Pool Traffic In/Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsIn{members=~\"\", job='$job', instance='$instance'}[$__rate_interval])",
     "legendFormat": "Bits-In {{pools}}"
    },
    {
     "expr": "rate(f5_serverside_bitsOut{members=~\"\", job='$job', instance='$instance'}[$__rate_interval])",
     "legendFormat": "Bits-Out {{pools}}"
    }
   ]
  },
  {
   "title": "Pool Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true
  },
  {
   "title": "Pool Member Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "f5_serverside_curConns{job='$job', members=~'.+', instance='$instance'}",
     "legendFormat": "{{members}}"
    }
   ]
  },
  {
   "title": "Pool Member Traffic In/Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsIn{members=~\".+\", job='$job', instance='$instance'}[$__rate_interval])",
     "legendFormat": "Bits-In {{members}}"
    },
    {
     "expr": "rate(f5_serverside_bitsOut{members=~\".+\", job='$job', instance='$instance'}[$__rate_interval])",
     "legendFormat": "Bits-Out {{members}}"
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true
  },
  {
   "title": "Client SSL Protocols",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(f5_protocolUses_sslv3{clientSslProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (clientSslProfiles)"
    },
    {
     "expr": "sum (increase(f5_protocolUses_tlsv1{clientSslProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (clientSslProfiles)"
    },
    {
     "expr": "sum (increase(f5_protocolUses_tlsv1_1{clientSslProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (clientSslProfiles)"
    },
    {
     "expr": "sum (increase(f5_protocolUses_tlsv1_2{clientSslProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (clientSslProfiles)"
    },
    {
     "expr": "sum (increase(f5_protocolUses_tlsv1_3{clientSslProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (clientSslProfiles)"
    }
   ]
  },
  {
   "title": "HTTP Profiles",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(f5_2xxResp{httpProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (httpProfiles)"
    },
    {
     "expr": "sum (increase(f5_3xxResp{httpProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (httpProfiles)"
    },
    {
     "expr": "sum (increase(f5_4xxResp{httpProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (httpProfiles)"
    },
    {
     "expr": "sum (increase(f5_5xxResp{httpProfiles=~\".+\", job='$job', instance='$instance'}[$__range])) by (httpProfiles)"
    }
   ]
  }
 ]
}